# Work based on https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml
header:
  title: Playful Progressions Therapy
  subtitle: Nurturing Development Through Play
  buttons:
    - label: Contact Maria
      link: "#book"
      class: btn-primary
    # - label: Learn More
    #   link: "#services"

about:
  section: about
  title: "Pediatric Occupational Therapy"
  subtitle: "Nurturing Development Through Play"
  body: "At Playful Progressions, we believe every child deserves the opportunity to grow, learn, and thrive through the power of play—the most important occupation of childhood! We are dedicated to creating a collaborative approach to therapy, working closely with families and schools to develop personalized strategies tailored to each child's unique needs. By focusing on the child's natural environment—whether at home or school—we ensure meaningful progress that enhances their development and success."
  location: Atlanta, GA
  neighborhoods:
    - Brookhaven
    - Buckhead
    - Chamblee
    - Sandy Springs
    - Dunwoody
    - Midtown
  what-we-treat:
    - title: Infants
      items:
        - Sensory processing and regulation
        - Bodywork for movement and alignment
        - Torticollis and plagiocephaly treatment
        - Reflex integration for early motor development
    - title: Toddlers & Young Children
      items:
        - Fine and gross motor skill development
        - Sensory integration and self-regulation
        - Handwriting and school-related tasks
        - Activities of daily living (dressing, feeding, hygiene)
        - Coordination, balance, and motor planning
        - Social skills and emotional regulation

testimonial:
  section: testimonial
  title: What parents say
  quotes:
    - text: "<b>Mrs. Maria is an angel on earth!</b> My daughter has dyspraxia and speech apraxia - what Maria did with my daughter's progress in a year is TRULY REMARKABLE!!!! Mrs. Maria is the exact type of person that you want your child to be with because her warmth coupled with her ability to make everything fun - while also learning - is a gift unlike anything I have ever seen! <b>I can not recommend Mrs. Maria enough!</b>"
      name: "Emily & 4yo daughter"
    - text: "As a new mom, <b>I wasn't sure if my baby's development was on track</b>. She hated tummy time and seemed easily overwhelmed by touch. Mrs. Maria helped me understand her sensory needs and gave me simple, loving ways to support her at home. Now our daughter is so much more curious, confident, and engaged in play. Mrs. Maria's calm presence and insight brought real relief — <b>we're so grateful we found her when we did!</b>"
      name: "Sydney & baby girl"
    - text: "<b>Mrs. Maria has been such a gift to our family!!</b> Our son really struggled with transitions and staying focused at school — every day felt like a challenge. Starting in the first session Mrs. Maria built a strong connection with him and gave us tools that actually made a difference. We've seen real progress: mornings are smoother, and he's so much more present in class. <b>Her guidance and compassion have made all the difference, and we're endlessly thankful for her support.</b>"
      name: "Lexi & 6yo son"

team:
  section: team
  title: "Meet Maria"
  subtitle: "Caring, experienced, engaging therapy"
  subtext:
    "**Hi, I'm Maria O'Farrell, MS, OTR/L**, a passionate pediatric occupational therapist and the proud owner of Playful Progressions! With over eight years of experience, I've had the privilege of working with children and adolescents (ages 0-21) in various settings, including outpatient clinics, homes, and schools. \n\n
    At Playful Progressions, I provide comprehensive occupational therapy evaluations and personalized interventions in homes and schools, ensuring that each child receives the support they need in a familiar and comfortable environment. My approach is rooted in collaboration, practicality, and kindness—I believe in offering individualized, judgment-free guidance to families navigating sensory differences and developmental milestones. \n\n
    I'm dedicated to helping children build confidence, independence, and essential life skills through play-based, engaging therapy. I'd love to be part of your child's journey!"
  people:
    - name: "Maria O'Farrell"
      role: "Owner"
      image: assets/img/maria_headshot.avif
  training:
    - Sensory Integration
    - Neurodevelopmental Treatment (NDT) strategies
    - Reflex Integration
    - Handwriting Without Tears
    - Eye Movement Disorders Training
    - Astronaut Training
    - Torticollis and Plagiocephaly
    - Feeding Therapy

services:
  title: "Services"
  subtitle: "A full suite of pediatric therapy needs"
  section: services # This section ID might still be useful for the home page link
  list: # Keep the existing list for the home page section
    - title: "Initial Evaluation"
      desc: "Comprehensive occupational therapy evaluation including standard assessment, skilled observations, parent interview and plan of care development with full write up (60-90 minutes)"
      image: assets/img/baby-crawling.avif
      icon: fas fa-notes-medical
    - title: "OT Treatment"
      image: assets/img/kid-ot-playing.avif
      desc: "Skilled, individualized occupational therapy treatment provided in the client's natural environment (home/school). Treatments are 50 minutes in duration, with 10 minutes of parent education and guidance for home programming between visits"
      icon: fa-solid fa-plane-up
    - title: "Consultations"
      desc: "Virtual consultations/coaching sessions for caregivers, other providers, and schools. Sessions are designed to provide guidance for improving a child's experience across contexts, as well as generating a support system for carrying-over care"
      image: assets/img/baby-playing-game.avif
      icon: fas fa-clipboard #find more at https://fontawesome.com/icons

  # New detailed list for the services page
  detailed_list:
    - id: "evaluations" # ID for mini-nav link
      title: "OT Evaluations"
      description: "A comprehensive evaluation to understand your child's unique needs and strengths."
      tiers:
        - name: "Foundational Evaluation"
          description: "Includes clinical observations, parent interview, and initial recommendations."
          includes:
            - Clinical observations
            - Sensory Processing Measure assessment (SPM-2)
            - In-depth intake call with caregiver
            - Brief written summary of findings
            - Initial recommendations
        - name: "Comprehensive Evaluation"
          description: "Includes all foundational elements plus in-depth analysis, detailed report, and follow-up consultation. Recommended if we plan to submit for reimbursement"
          includes:
            - (+) Standardized assessments (PDMS-3, .....)
            - Clinical observations
            - Sensory Processing Measure assessment (SPM-2)
            - In-depth intake call with caregiver
            - Brief written summary of findings
            - Initial recommendations
            - (+) Follow-up consultation to review findings and plan

    - id: "treatments"
      title: "OT Treatments"
      description: "Individualized therapy sessions focused on achieving specific developmental goals."
      tiers:
        - name: "Foundational Treatment"
          description: "Regular therapy sessions in the child's natural environment."
          includes:
            - 50-minute direct therapy session
            - 10-minute parent/caregiver education and home program guidance
            - Therapy provided in home or school setting
        - name: "Comprehensive Treatment Package" # Example of slightly different tier name
          description: "Includes foundational treatment plus enhanced support and resources."
          includes:
            - 50-minute direct therapy session
            - 10-minute parent/caregiver education and home program guidance
            - Therapy provided in home or school setting
            - Access to exclusive home program resources
            - Priority scheduling

    - id: "consultations"
      title: "OT Consultations"
      description: "Guidance and support for caregivers, educators, and other professionals."
      tiers:
        - name: "Foundational Consultation"
          description: "Single virtual session to address specific questions or concerns."
          includes:
            - 60-minute virtual consultation session
            - Discussion of specific challenges and strategies
        - name: "Comprehensive Consultation Package"
          description: "Multiple virtual sessions and ongoing support."
          includes:
            - Three 60-minute virtual consultation sessions
            - Ongoing email support between sessions
            - Collaborative strategy development

book:
  title: "Contact"
  section: book
  subtitle: "Speak with Maria to determine the best course for your child"

footer:
  legal: "Privacy Policy"
  social:
    # - url: https://twitter.com
    #   icon: "fab fa-twitter"
    # - url: https://facebook.com
    #   icon: "fab fa-facebook-f"
    # - url: https://linkedin.com
    #   icon: "fab fa-linkedin-in"
    # - url: https://github.com/raviriley/agency-jekyll-theme
    #   icon: "fab fa-github"
    - url: https://instagram.com
      icon: "fab fa-instagram"

# FAQ Content
faq: # New section for FAQ
  title: "Your Questions Answered"
  subtitle: "Find information about payments, insurance, appointments, and more."
  items:
    - question: "What is your payment process?"
      answer: |
        All payments are securely processed through our HIPAA-compliant payment processor, Jane Payments. When you schedule your child's initial evaluation, you will complete intake forms where you can safely enter your credit card, HSA, or FSA information to be kept on file. Your card will be charged at the time of service.

    - question: "What is your cancellation policy?"
      answer: |
        We understand that scheduling changes can happen! To ensure we can provide dedicated care to all families, we require advance notice for cancellations or rescheduling.

        * Cancellations made within **48 hours** of your appointment will incur a **25% fee** of the session cost.
        * Cancellations made within **24 hours** of your appointment will be charged **50%** of the session fee.

        Your understanding and cooperation are greatly appreciated!

    - question: "Do you accept insurance?"
      answer: |
        Playful Progressions operates as a **private-pay practice** and does not directly accept commercial insurance. However, many insurance plans offer reimbursement for services received from an out-of-network provider.

        We are happy to provide you with a **superbill** that you can submit to your insurance company for potential reimbursement. Our superbills include commonly used treatment codes such as Therapeutic Activity (97530) and Occupational Therapy Initial Evaluation (97165, 97166, 97167).

        We strongly recommend contacting your insurance provider directly to understand your specific out-of-network benefits and reimbursement options. We are available to help guide you through this process if you have questions.

    - question: "Why choose private pay over in-network providers?"
      answer: |
        While using insurance can be beneficial, in-network providers often have long waiting lists, which can delay essential support for your child. As a private-pay practice, Playful Progressions can offer services more immediately, helping to bridge that gap.

        Additionally, insurance coverage is frequently subject to deductibles and coinsurance, meaning you may still have out-of-pocket costs. Our focus is on providing high-quality, individualized therapy without unnecessary delays, ensuring your child receives timely support for their development.
